### Get Game
GET localhost:3000/api/game/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiaHVmZmYiLCJpZCI6OSwiaWF0IjoxNjg1NjM0OTM5fQ.PZ7VFbmwDjkOE3Oqo0KudNs86_h3OYmjYrRjeZfqSR8