// example token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiaHVmZmYiLCJpZCI6OSwiaWF0IjoxNjg1NjM0OTM5fQ.PZ7VFbmwDjkOE3Oqo0KudNs86_h3OYmjYrRjeZfqSR8

### Get all Games
GET localhost:3000/api/new_game/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiaHVmZmYiLCJpZCI6OSwiaWF0IjoxNjg1NjM0OTM5fQ.PZ7VFbmwDjkOE3Oqo0KudNs86_h3OYmjYrRjeZfqSR8

### Get all Games - no Auth
GET localhost:3000/api/new_game/

### Get all Games - invalid Auth
GET localhost:3000/api/new_game/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiaHVmZmYiLCJpZCI6OSwiaWF0IjoxNjg1NjM0OTM5fQ.PZ7VFbmwDjkOE3Oqo0KudNs86_h3OYmjYrRjeZfqSR8

### Create game Game
POST localhost:3000/api/new_game/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiaHVmZmYiLCJpZCI6OSwiaWF0IjoxNjg1NjM0OTM5fQ.PZ7VFbmwDjkOE3Oqo0KudNs86_h3OYmjYrRjeZfqSR8
Content-Type: application/json

{
  "timestamp": 5,
  "name": "huff"
}

### Create game Game - no Auth
GET localhost:3000/api/new_game/
Content-Type: application/json

{
  "timestamp": 5,
  "name": "huff"
}

### Create game Game - invalid Auth
GET localhost:3000/api/new_game/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiaHVmZmYiLCJpZCI6OSwiaWF0IjoxNjg1NjM0OTM5fQ.PZ7VFbmwDjkOE3Oqo0KudNs86_h3OYmjYrRjeZfqSR8
Content-Type: application/json

{
  "timestamp": 5,
  "name": "huff"
}