### login
POST localhost:3000/api/user/login
Content-Type: application/json

{
  "userName": "hufff",
  "password": "123"
}

### register
POST localhost:3000/api/user/register
Content-Type: application/json

{
  "userName": "hufff",
  "password": "123"
}